#!/usr/bin/env bash

set -euo pipefail

readonly SELF="$(basename ${BASH_SOURCE[0]})"
readonly SELF_DIR="$(cd $(dirname $(readlink -f ${BASH_SOURCE[0]})) > /dev/null 2>&1 && pwd)"
readonly OS="$(uname)"
readonly VERSION="1.0.0"

OPT_HELP=
OPT_DEBUG=
OPT_VERBOSE=
OPT_VERSION=

VAL_SCREEN_LOG_FILE=/tmp/mkadm.${RANDOM}.log

function error () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "ERROR: ${@}" >&2
  else
    echo -e "\e[0;31m\e[1mERROR: \e[0;0m${@}" >&2
  fi

  exit 1
}

function warn () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "WARNING: ${@}" >&2
  else
    echo -e "\e[0;33mWARNING: \e[0;0m${@}" >&2
  fi
}

function debug () {
  if [[ -n "${OPT_DEBUG}" ]]; then
    echo -n "** "
    echo "\${PWD}: ${PWD}"
    echo "\${@}: ${@}"
  fi
}

function parse_arguments () {
  debug ${FUNCNAME[0]} "$@"

  local opts=$(getopt -n "${SELF}" --options h --longoptions help,debug,verbose,version -- "$@")

  if [[ $? != 0 ]]; then
    error "Failed to parse arguments. Aborting."
  fi

  eval set -- "${opts}"

  while true; do
    case "$1" in
      (--help) OPT_HELP=true; shift ;;
      (--debug) OPT_DEBUG=true; shift ;;
      (--verbose) OPT_VERBOSE=true; shift ;;
      (--version) OPT_VERSION=true; shift ;;
      (--) shift; break ;;
      (*) break ;;
    esac
  done
}
function process_arguments () {
  debug ${FUNCNAME[0]} "$@"

  if [[ -n "${OPT_HELP}"  || "${#}" -eq 0 ]]; then
    display_usage
  elif [[ -n "${OPT_VERSION}" ]]; then
    display_version
  else
    return 0
  fi
}

function display_usage () {
  debug ${FUNCNAME[0]} "$@"

  cat << EOF
${SELF} v${VERSION} [OPTIONS]...

OPTIONS:
      --help                    Show this help
      --debug                   Enable debugging mode
      --verbose                 Enable verbose output
      --version                 Display program version info
EOF
  exit 0
}


function display_version () {
  debug ${FUNCNAME[0]} "$@"

  cat << EOF
${SELF} v${VERSION}
EOF
  exit 0
}

function stage () {
  debug ${FUNCNAME[0]} "$@"

  if [[ -f "${VAL_SCREEN_LOG_FILE}" ]]; then
    rm -f "${VAL_SCREEN_LOG_FILE}"
  fi
}

function run () {
  debug ${FUNCNAME[0]} "$@"

  local name=
  local email=

  if [[ $# -eq 2 ]]; then
    name=$1
    email=$2
    screen -L -Logfile "${VAL_SCREEN_LOG_FILE}" -dmS mkadm mkadm -n "${name}" -e "${email}"
  else
    display_usage
  fi
}

function main () {
  debug ${FUNCNAME[0]} "$@"

  parse_arguments "$@"
  process_arguments "$@"

  stage
  run "$@"
}

main "$@"
