#!/usr/bin/env bash

set -eu
set -o pipefail

readonly SELF=$(basename "${BASH_SOURCE[0]}")
readonly OS=$(uname)
readonly VERSION=1.0.0

readonly OPT_BASE_NAME=${SELF}

OPT_HELP=
OPT_DEBUG=
OPT_VERBOSE=

function error () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "error: ${@}" >&2
  else
    echo -e "\e[0;31m\e[1merror: \e[0;0m${@}" >&2
  fi

  exit 1
}

function warn () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "warning: ${@}" >&2
  else
    echo -e "\e[0;33mwarning: \e[0;0m${@}" >&2
  fi
}

function debug () {
  if [[ -n "${OPT_DEBUG}" ]]; then
    echo '**'
    echo \${@}: ${@}
    echo \$OPT_DEBUG: "${OPT_DEBUG}"
  fi
}

function parse_arguments () {
  debug ${FUNCNAME[0]} "$@"

  local opts=$(getopt -n "${SELF}" --options hdv --longoptions help,debug,verbose -- "$@")

  if [[ $? != 0 ]]; then
    error "Failed to parse arguments. Exiting."
  fi

  eval set -- "${opts}"

  while true; do
    case "$1" in
      (-h|--help) OPT_HELP=true; shift ;;
      (-d|--debug) OPT_DEBUG=true; shift ;;
      (-v|--verbose) OPT_VERBOSE=true; shift ;;
      (--) shift; break ;;
      (*) break ;;
    esac
  done
}

function process_arguments () {
  debug ${FUNCNAME[0]} "$@"

  if [[ -n "${OPT_HELP}" || "${#}" -lt 1 ]]; then
    display_usage
  else
    return 0
  fi
}

function display_usage () {
  debug ${FUNCNAME[0]} "$@"

  cat << EOF
${SELF} [OPTIONS]... <DROPLET>

OPTIONS:
  -h, --help       Show this help
  -d, --debug      Enable debugging mode
  -v, --verbose    Enable verbose output
EOF
  exit 0
}

function update_files () {
  debug ${FUNCNAME[0]} "$@"

  for i in $(rg -l 'wiki\.js\.org'); do
    sed -i -e 's/wiki\.js\.org/miki.mimix.org/g' "$i"
  done

  for i in $(rg -l 'Wiki\.js'); do
    sed -i -e 's/Wiki\.js/Miki/g' "$i"
  done

  for i in $(rg -l 'WIKI\.js'); do
    sed -i -e 's/WIKI\.js/Miki/g' "$i"
  done

  for i in $(rg -l 'wiki\.js'); do
    sed -i -e 's/wiki\.js/miki/g' "$i"
  done

  for i in $(rg -l 'wiki-js'); do
    sed -i -e 's/wiki-js/miki/g' "$i"
  done

  for i in $(rg -l 'wikijs'); do
    sed -i -e 's/wikijs/miki/g' "$i"
  done
}

function main () {
  debug ${FUNCNAME[0]} "$@"

  parse_arguments "$@"
  process_arguments "$@"
}

main "$@"
