#!/usr/bin/env bash

set -eu
set -o pipefail

readonly SELF=$(basename "${BASH_SOURCE[0]}")
readonly SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly OS=$(uname)
readonly VERSION=1.0.5

readonly OPT_BASE_NAME=${SELF}

OPT_HELP=
OPT_DEBUG=
OPT_VERBOSE=

OPT_RESOURCES_DIR=${SELF_DIR}/resources
OPT_ASSETS_DIR=${OPT_RESOURCES_DIR}/assets

OPT_WIKI_NAME=
OPT_WIKI_DOMAIN=
OPT_WIKI_RESOURCES=
OPT_WIKI_GITHUB=
OPT_COMPANY_NAME=

function error () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "error: ${@}" >&2
  else
    echo -e "\e[0;31m\e[1merror: \e[0;0m${@}" >&2
  fi

  exit 1
}

function warn () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "warning: ${@}" >&2
  else
    echo -e "\e[0;33mwarning: \e[0;0m${@}" >&2
  fi
}

function debug () {
  if [[ -n "${OPT_DEBUG}" ]]; then
    echo '**'
    echo \${@}: ${@}
    echo \$OPT_DEBUG: "${OPT_DEBUG}"
  fi
}

function parse_arguments () {
  debug ${FUNCNAME[0]} "$@"

  local opts=$(getopt -n "${SELF}" --options hdvN:D:G:C:R: --longoptions help,debug,verbose,wiki-name:,wiki-domain:,wiki-resources:,wiki-github:,company-name: -- "$@")

  if [[ $? != 0 ]]; then
    error "Failed to parse arguments. Exiting."
  fi

  eval set -- "${opts}"

  while true; do
    case "$1" in
      (-h|--help) OPT_HELP=true; shift ;;
      (-d|--debug) OPT_DEBUG=true; shift ;;
      (-v|--verbose) OPT_VERBOSE=true; shift ;;
      (-N|--wiki-name) OPT_WIKI_NAME=$2; shift 2 ;;
      (-D|--wiki-domain) OPT_WIKI_DOMAIN=$2; shift 2 ;;
      (-R|--wiki-resources) OPT_WIKI_RESOURCES=$2; shift 2 ;;
      (-G|--wiki-github) OPT_WIKI_GITHUB=$2; shift 2 ;;
      (-C|--company-name) OPT_COMPANY_NAME=$2; shift 2 ;;
      (--) shift; break ;;
      (*) break ;;
    esac
  done
}

function process_arguments () {
  debug ${FUNCNAME[0]} "$@"

  if [[ -n "${OPT_HELP}" || "${#}" -lt 1 ]]; then
    display_usage
  elif [[ -z "${OPT_WIKI_NAME}" || -z "${OPT_WIKI_DOMAIN}" || -z "${OPT_WIKI_RESOURCES}" || -z "${OPT_WIKI_GITHUB}" || -z "${OPT_COMPANY_NAME}" ]]; then
    display_usage
  else
    return 0
  fi
}

function display_usage () {
  debug ${FUNCNAME[0]} "$@"

  cat << EOF
${SELF} [OPTIONS]...

OPTIONS:
  -h, --help            Show this help
  -d, --debug           Enable debugging mode
  -v, --verbose         Enable verbose output
  -N, --wiki-name       Set wiki name
  -D, --wiki-domain     Set wiki domain
  -R, --wiki-resources  Set URL of wiki resources
  -G, --wiki-github     Set URL of wiki GitHub page
  -C, --company-name    Set company name
EOF
  exit 0
}

function set_substitutions () {
  # echo "${VAR^}"
  declare -A SUBSTITUTIONS=(
    ['https://static\.requarks\.io/logo']="${OPT_WIKI_RESOURCES}"
    ['https://github\.com/Requarks/wiki']="${OPT_WIKI_GITHUB}"

    ['wiki\.yourdomain\.com']="${OPT_WIKI_DOMAIN}"
    ['wiki\.js\.org']="${OPT_WIKI_DOMAIN}"
    ['Wiki\.js']="${OPT_WIKI_NAME^}"
    ['WIKI\.js']="${OPT_WIKI_NAME^}"
    ['wiki\.js']="${OPT_WIKI_NAME}"
    ['wiki-js']="${OPT_WIKI_NAME}"
    ['wikijs']="${OPT_WIKI_NAME}"

    #['requarks\.io']='mimix.io'
    #['requarks']='mimix'
    #['Requarks']='Mimix'

    # workaround
    ['miki-butterfly\.svg']="${OPT_COMPANY_NAME}.svg"
  )
}

function initialize () {
  debug ${FUNCNAME[0]} "$@"

  if [[ -e "package.json" && "$(jq '.name' package.json)" == \"wiki\" ]]; then
    return 0
  else
    error "!"
  fi
}

function update_files () {
  debug ${FUNCNAME[0]} "$@"

  declare -A SUBSTITUTIONS=(
    ['https://static\.requarks\.io/logo']="${OPT_WIKI_RESOURCES}"
    ['https://github\.com/Requarks/wiki']="${OPT_WIKI_GITHUB}"

    ['wiki\.yourdomain\.com']="${OPT_WIKI_DOMAIN}"
    ['wiki\.js\.org']="${OPT_WIKI_DOMAIN}"
    ['Wiki\.js']="${OPT_WIKI_NAME^}"
    ['WIKI\.js']="${OPT_WIKI_NAME^}"
    ['wiki\.js']="${OPT_WIKI_NAME}"
    ['wiki-js']="${OPT_WIKI_NAME}"
    ['wikijs']="${OPT_WIKI_NAME}"

    #['requarks\.io']='mimix.io'
    #['requarks']='mimix'
    #['Requarks']='Mimix'

    # workaround?
    ['miki-butterfly\.svg']="${OPT_COMPANY_NAME}.svg"
  )

  for i in "${!SUBSTITUTIONS[@]}"; do
    for file in $(rg -l "$i"); do
      sed -i -e "s|${i}|${SUBSTITUTIONS[$i]}|g" "$file"
    done
  done
}

function delete_files () {
  debug ${FUNCNAME[0]} "$@"

  rm -f README.md SECURITY.md
  rm -rf .github

  rm -f assets/favicon.ico
  rm -rf assets/favicons
  rm -f assets/svg/logo-wikijs.svg
  rm -f assets/svg/logo-wikijs-full.svg
}

function create_readme () {
  debug ${FUNCNAME[0]} "$@"

  cat << EOF > README.md
# miki
EOF
}

function install_assets () {
  debug ${FUNCNAME[0]} "$@"

  rsync -a ${OPT_ASSETS_DIR}/favicon.ico assets
  rsync -a ${OPT_ASSETS_DIR}/favicons assets
  rsync -a ${OPT_ASSETS_DIR}/svg assets
}

function install_resources () {
  debug ${FUNCNAME[0]} "$@"

  install_assets
}

function main () {
  debug ${FUNCNAME[0]} "$@"

  parse_arguments "$@"
  process_arguments "$@"

  initialize "$@"
  update_files
  delete_files
  create_readme
  install_resources
}

main "$@"
